#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR)
echo running format on staged files = $STAGED_FILES

./venv/Scripts/activate.bat

python -m scripts.format $STAGED_FILES

echo staging files = $STAGED_FILES
git add -f $STAGED_FILES

# for file in $STAGED_FILES
# do
#   yapf -i $file
#   git add $file
# done;

exit 0
