#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR)
echo STAGED_FILES: $STAGED_FILES

# deprecated formatting
# for file in $STAGED_FILES
# do
#     [[ $file =~ ^.+\.py$ ]] || continue
#     echo yapf -i $file
#     yapf -i $file
#     git add $file
# done;

# update requirements
echo pip freeze > requirements.txt
pip freeze > requirements.txt
git add requirements.txt

# run formatter script
echo python -m scripts.format
python -m scripts.format
git add -f $STAGED_FILES

# run linter script
echo python -m scripts.lint
python -m scripts.lint
LINTER_EXIT_CODE=$?

if [ $LINTER_EXIT_CODE -ne 0 ]; then
    echo "Linter error, commit aborted"
    exit 1
fi

exit 0
